# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_sys_mb_0/system_sys_mb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_mb_0 || ORIG_REF_NAME==system_sys_mb_0}]

# IP: bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_dlmb_0 || ORIG_REF_NAME==system_sys_dlmb_0}]

# IP: bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ilmb_0 || ORIG_REF_NAME==system_sys_ilmb_0}]

# IP: bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_dlmb_cntlr_0 || ORIG_REF_NAME==system_sys_dlmb_cntlr_0}]

# IP: bd/system/ip/system_sys_ilmb_cntlr_0/system_sys_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ilmb_cntlr_0 || ORIG_REF_NAME==system_sys_ilmb_cntlr_0}]

# IP: bd/system/ip/system_sys_lmb_bram_0/system_sys_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_lmb_bram_0 || ORIG_REF_NAME==system_sys_lmb_bram_0}]

# IP: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_mb_debug_0 || ORIG_REF_NAME==system_sys_mb_debug_0}]

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0}]

# IP: bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_0}]

# IP: bd/system/ip/system_sys_ethernet_clkgen_0/system_sys_ethernet_clkgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ethernet_clkgen_0 || ORIG_REF_NAME==system_sys_ethernet_clkgen_0}]

# IP: bd/system/ip/system_axi_ethernet_0/system_axi_ethernet_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ethernet_0 || ORIG_REF_NAME==system_axi_ethernet_0}]

# Block Designs: bd/system/ip/system_axi_ethernet_0/bd_0/bd_55cd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_55cd || ORIG_REF_NAME==bd_55cd}]

# IP: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/bd_55cd_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_55cd_eth_buf_0 || ORIG_REF_NAME==bd_55cd_eth_buf_0}]

# IP: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/bd_55cd_eth_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_55cd_eth_mac_0 || ORIG_REF_NAME==bd_55cd_eth_mac_0}]

# IP: bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ethernet_dma_0 || ORIG_REF_NAME==system_axi_ethernet_dma_0}]

# IP: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0}]

# IP: bd/system/ip/system_axi_uart_0/system_axi_uart_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart_0 || ORIG_REF_NAME==system_axi_uart_0}]

# IP: bd/system/ip/system_axi_timer_0/system_axi_timer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_timer_0 || ORIG_REF_NAME==system_axi_timer_0}]

# IP: bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_lcd_0 || ORIG_REF_NAME==system_axi_gpio_lcd_0}]

# IP: bd/system/ip/system_axi_spi_0/system_axi_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0}]

# IP: bd/system/ip/system_axi_gpio_0/system_axi_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0 || ORIG_REF_NAME==system_axi_gpio_0}]

# IP: bd/system/ip/system_axi_intc_0/system_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0}]

# IP: bd/system/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0}]

# IP: bd/system/ip/system_axi_ddr_cntrl_device_temp_i_GND_0/system_axi_ddr_cntrl_device_temp_i_GND_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_device_temp_i_GND_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_device_temp_i_GND_0}]

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_axi_mem_interconnect_0/system_axi_mem_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_interconnect_0 || ORIG_REF_NAME==system_axi_mem_interconnect_0}]

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1}]

# IP: bd/system/ip/system_axi_hdmi_clkgen_0/system_axi_hdmi_clkgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hdmi_clkgen_0 || ORIG_REF_NAME==system_axi_hdmi_clkgen_0}]

# IP: bd/system/ip/system_axi_hdmi_core_0/system_axi_hdmi_core_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hdmi_core_0 || ORIG_REF_NAME==system_axi_hdmi_core_0}]

# IP: bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hdmi_dma_0 || ORIG_REF_NAME==system_axi_hdmi_dma_0}]

# IP: bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_audio_clkgen_0 || ORIG_REF_NAME==system_sys_audio_clkgen_0}]

# IP: bd/system/ip/system_axi_spdif_tx_core_0/system_axi_spdif_tx_core_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_core_0 || ORIG_REF_NAME==system_axi_spdif_tx_core_0}]

# IP: bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_dma_0 || ORIG_REF_NAME==system_axi_spdif_tx_dma_0}]

# IP: bd/system/ip/system_sys_mb_1/system_sys_mb_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_mb_1 || ORIG_REF_NAME==system_sys_mb_1}]

# IP: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_0 || ORIG_REF_NAME==system_dlmb_v10_0}]

# IP: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_0 || ORIG_REF_NAME==system_ilmb_v10_0}]

# IP: bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_dlmb_bram_if_cntlr_0}]

# IP: bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_ilmb_bram_if_cntlr_0}]

# IP: bd/system/ip/system_lmb_bram_0/system_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_0 || ORIG_REF_NAME==system_lmb_bram_0}]

# IP: bd/system/ip/system_sys_mb1_axi_periph_0/system_sys_mb1_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_mb1_axi_periph_0 || ORIG_REF_NAME==system_sys_mb1_axi_periph_0}]

# IP: bd/system/ip/system_sys_mb1_axi_intc_0/system_sys_mb1_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_mb1_axi_intc_0 || ORIG_REF_NAME==system_sys_mb1_axi_intc_0}]

# IP: bd/system/ip/system_xbar_2/system_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_2 || ORIG_REF_NAME==system_xbar_2}]

# IP: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_timer_0_0 || ORIG_REF_NAME==system_axi_timer_0_0}]

# IP: bd/system/ip/system_mailbox_0_0/system_mailbox_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mailbox_0_0 || ORIG_REF_NAME==system_mailbox_0_0}]

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0}]

# IP: bd/system/ip/system_mutex_0_0/system_mutex_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mutex_0_0 || ORIG_REF_NAME==system_mutex_0_0}]

# IP: bd/system/ip/system_s05_data_fifo_0/system_s05_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s05_data_fifo_0 || ORIG_REF_NAME==system_s05_data_fifo_0}]

# IP: bd/system/ip/system_auto_us_df_0/system_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_0 || ORIG_REF_NAME==system_auto_us_df_0}]

# IP: bd/system/ip/system_auto_us_df_1/system_auto_us_df_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_1 || ORIG_REF_NAME==system_auto_us_df_1}]

# IP: bd/system/ip/system_auto_us_df_2/system_auto_us_df_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_2 || ORIG_REF_NAME==system_auto_us_df_2}]

# IP: bd/system/ip/system_auto_us_df_3/system_auto_us_df_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_3 || ORIG_REF_NAME==system_auto_us_df_3}]

# IP: bd/system/ip/system_auto_us_df_4/system_auto_us_df_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_4 || ORIG_REF_NAME==system_auto_us_df_4}]

# IP: bd/system/ip/system_auto_us_df_5/system_auto_us_df_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_5 || ORIG_REF_NAME==system_auto_us_df_5}]

# IP: bd/system/ip/system_auto_us_df_6/system_auto_us_df_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_6 || ORIG_REF_NAME==system_auto_us_df_6}]

# IP: bd/system/ip/system_auto_us_df_7/system_auto_us_df_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_7 || ORIG_REF_NAME==system_auto_us_df_7}]

# IP: bd/system/ip/system_auto_us_df_8/system_auto_us_df_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_df_8 || ORIG_REF_NAME==system_auto_us_df_8}]

# XDC: bd/system/ip/system_sys_mb_0/system_sys_mb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_mb_0 || ORIG_REF_NAME==system_sys_mb_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_mb_0/system_sys_mb_0_ooc_debug.xdc

# XDC: bd/system/ip/system_sys_mb_0/system_sys_mb_0_ooc.xdc

# XDC: bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_dlmb_0 || ORIG_REF_NAME==system_sys_dlmb_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0_ooc.xdc

# XDC: bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ilmb_0 || ORIG_REF_NAME==system_sys_ilmb_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0_ooc.xdc

# XDC: bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0_ooc.xdc

# XDC: bd/system/ip/system_sys_ilmb_cntlr_0/system_sys_ilmb_cntlr_0_ooc.xdc

# XDC: bd/system/ip/system_sys_lmb_bram_0/system_sys_lmb_bram_0_ooc.xdc

# XDC: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_mb_debug_0 || ORIG_REF_NAME==system_sys_mb_debug_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0_ooc_trace.xdc

# XDC: bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0_ooc.xdc

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/constraints/system_axi_ddr_cntrl_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0 || ORIG_REF_NAME==system_axi_ddr_cntrl_0}]

# XDC: bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/constraints/system_axi_ddr_cntrl_0_ooc.xdc

# XDC: bd/system/ip/system_sys_ethernet_clkgen_0/system_sys_ethernet_clkgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ethernet_clkgen_0 || ORIG_REF_NAME==system_sys_ethernet_clkgen_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_sys_ethernet_clkgen_0/system_sys_ethernet_clkgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ethernet_clkgen_0 || ORIG_REF_NAME==system_sys_ethernet_clkgen_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_sys_ethernet_clkgen_0/system_sys_ethernet_clkgen_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/bd_55cd_eth_buf_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_55cd_eth_buf_0 || ORIG_REF_NAME==bd_55cd_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/synth/bd_55cd_eth_buf_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_55cd_eth_buf_0 || ORIG_REF_NAME==bd_55cd_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/bd_55cd_eth_buf_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_eth_mac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_55cd_eth_mac_0 || ORIG_REF_NAME==bd_55cd_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_eth_mac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_55cd_eth_mac_0 || ORIG_REF_NAME==bd_55cd_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_eth_mac_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_eth_mac_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_55cd_eth_mac_0 || ORIG_REF_NAME==bd_55cd_eth_mac_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_axi_ethernet_0/bd_0/bd_55cd_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_0/synth/system_axi_ethernet_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ethernet_dma_0 || ORIG_REF_NAME==system_axi_ethernet_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ethernet_dma_0 || ORIG_REF_NAME==system_axi_ethernet_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uart_0/system_axi_uart_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uart_0 || ORIG_REF_NAME==system_axi_uart_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_uart_0/system_axi_uart_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uart_0/system_axi_uart_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uart_0 || ORIG_REF_NAME==system_axi_uart_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_timer_0/system_axi_timer_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_timer_0 || ORIG_REF_NAME==system_axi_timer_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_timer_0/system_axi_timer_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_lcd_0 || ORIG_REF_NAME==system_axi_gpio_lcd_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_lcd_0 || ORIG_REF_NAME==system_axi_gpio_lcd_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0_ooc.xdc

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_0/system_axi_gpio_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0 || ORIG_REF_NAME==system_axi_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_0/system_axi_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0/system_axi_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0 || ORIG_REF_NAME==system_axi_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_intc_0/system_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_intc_0/system_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_intc_0/system_axi_intc_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc

# TCL: bd/system/ip/system_axi_hdmi_clkgen_0/bd/bd.tcl

# XDC: bd/system/ip/system_axi_hdmi_clkgen_0/axi_clkgen_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hdmi_clkgen_0 || ORIG_REF_NAME==system_axi_hdmi_clkgen_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/xilinx/common/up_xfer_cntrl_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_cntrl || ORIG_REF_NAME==up_xfer_cntrl}]

# XDC: bd/system/ip/xilinx/common/ad_rst_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ad_rst || ORIG_REF_NAME==ad_rst}]

# XDC: bd/system/ip/xilinx/common/up_xfer_status_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_status || ORIG_REF_NAME==up_xfer_status}]

# XDC: bd/system/ip/xilinx/common/up_clock_mon_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_clock_mon || ORIG_REF_NAME==up_clock_mon}]

# XDC: bd/system/ip/system_axi_hdmi_core_0/axi_hdmi_tx_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hdmi_core_0 || ORIG_REF_NAME==system_axi_hdmi_core_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hdmi_dma_0 || ORIG_REF_NAME==system_axi_hdmi_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hdmi_dma_0 || ORIG_REF_NAME==system_axi_hdmi_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_ooc.xdc

# XDC: bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_audio_clkgen_0 || ORIG_REF_NAME==system_sys_audio_clkgen_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_audio_clkgen_0 || ORIG_REF_NAME==system_sys_audio_clkgen_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_audio_clkgen_0 || ORIG_REF_NAME==system_sys_audio_clkgen_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_ooc.xdc

# XDC: bd/system/ip/system_axi_spdif_tx_core_0/axi_spdif_tx_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_core_0 || ORIG_REF_NAME==system_axi_spdif_tx_core_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0_ooc.xdc

# XDC: bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_dma_0 || ORIG_REF_NAME==system_axi_spdif_tx_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_dma_0 || ORIG_REF_NAME==system_axi_spdif_tx_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_mb_1/system_sys_mb_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_mb_1 || ORIG_REF_NAME==system_sys_mb_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_mb_1/system_sys_mb_1_ooc_debug.xdc

# XDC: bd/system/ip/system_sys_mb_1/system_sys_mb_1_ooc.xdc

# XDC: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_dlmb_v10_0 || ORIG_REF_NAME==system_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0_ooc.xdc

# XDC: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ilmb_v10_0 || ORIG_REF_NAME==system_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0_ooc.xdc

# XDC: bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/system/ip/system_lmb_bram_0/system_lmb_bram_0_ooc.xdc

# XDC: bd/system/ip/system_sys_mb1_axi_intc_0/system_sys_mb1_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_mb1_axi_intc_0 || ORIG_REF_NAME==system_sys_mb1_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_mb1_axi_intc_0/system_sys_mb1_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_mb1_axi_intc_0 || ORIG_REF_NAME==system_sys_mb1_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_sys_mb1_axi_intc_0/system_sys_mb1_axi_intc_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_2/system_xbar_2_ooc.xdc

# XDC: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_timer_0_0 || ORIG_REF_NAME==system_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0_ooc.xdc

# XDC: bd/system/ip/system_mailbox_0_0/system_mailbox_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mailbox_0_0 || ORIG_REF_NAME==system_mailbox_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mailbox_0_0/system_mailbox_0_0_ooc.xdc

# XDC: bd/system/ip/system_mutex_0_0/system_mutex_0_0_ooc.xdc

# XDC: bd/system/ip/system_s05_data_fifo_0/system_s05_data_fifo_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_0 || ORIG_REF_NAME==system_auto_us_df_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_1 || ORIG_REF_NAME==system_auto_us_df_1}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_2/system_auto_us_df_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_2 || ORIG_REF_NAME==system_auto_us_df_2}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_df_2/system_auto_us_df_2_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_3/system_auto_us_df_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_3 || ORIG_REF_NAME==system_auto_us_df_3}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_df_3/system_auto_us_df_3_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_4/system_auto_us_df_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_4 || ORIG_REF_NAME==system_auto_us_df_4}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_df_4/system_auto_us_df_4_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_5/system_auto_us_df_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_5 || ORIG_REF_NAME==system_auto_us_df_5}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_df_5/system_auto_us_df_5_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_6/system_auto_us_df_6_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_6 || ORIG_REF_NAME==system_auto_us_df_6}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_df_6/system_auto_us_df_6_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_7/system_auto_us_df_7_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_7 || ORIG_REF_NAME==system_auto_us_df_7}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_df_7/system_auto_us_df_7_ooc.xdc

# XDC: bd/system/ip/system_auto_us_df_8/system_auto_us_df_8_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_df_8 || ORIG_REF_NAME==system_auto_us_df_8}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_df_8/system_auto_us_df_8_ooc.xdc

# XDC: bd/system/system_ooc.xdc

# XDC: imports/FPGA/Analog_HDL/hdl-hdl_2017_r1/projects/common/ac701/ac701_system_constr.xdc

# XDC: imports/FPGA/HDMI_AC701/ac701_project_dual/system_constr.xdc
