# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {BD 41-1348}  -new_severity {INFO} 
set_msg_config  -ruleid {2}  -id {BD 41-1343}  -new_severity {INFO} 
set_msg_config  -ruleid {3}  -id {BD 41-1306}  -new_severity {INFO} 
set_msg_config  -ruleid {4}  -id {IP_Flow 19-1687}  -new_severity {INFO} 
set_msg_config  -ruleid {5}  -id {filemgmt 20-1763}  -new_severity {INFO} 
set_msg_config  -ruleid {6}  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR} 
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.cache/wt [current_project]
set_property parent.project_path D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.0 [current_project]
set_property ip_repo_paths d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.ipdefs/library_0 [current_project]
set_property ip_output_repo d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/imports/hdl/system_wrapper.v
  D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/imports/FPGA/Analog_HDL/hdl-hdl_2017_r1/library/xilinx/common/ad_iobuf.v
  D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/imports/FPGA/HDMI_AC701/ac701_project_dual/system_top.v
}
add_files D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_0/system_sys_mb_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_0/system_sys_mb_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_0/system_sys_mb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_dlmb_0/system_sys_dlmb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_ilmb_0/system_sys_ilmb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_ilmb_cntlr_0/system_sys_ilmb_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_lmb_bram_0/system_sys_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/constraints/system_axi_ddr_cntrl_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/constraints/system_axi_ddr_cntrl_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_ethernet_clkgen_0/system_sys_ethernet_clkgen_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_ethernet_clkgen_0/system_sys_ethernet_clkgen_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_ethernet_clkgen_0/system_sys_ethernet_clkgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/bd_55cd_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/synth/bd_55cd_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/bd_55cd_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_eth_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_eth_mac_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_eth_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_eth_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/bd_55cd_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/synth/system_axi_ethernet_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_dma_0/system_axi_ethernet_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_uart_0/system_axi_uart_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_uart_0/system_axi_uart_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_uart_0/system_axi_uart_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_timer_0/system_axi_timer_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_timer_0/system_axi_timer_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_gpio_lcd_0/system_axi_gpio_lcd_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_gpio_0/system_axi_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_gpio_0/system_axi_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_gpio_0/system_axi_gpio_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_intc_0/system_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_intc_0/system_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_intc_0/system_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_hdmi_clkgen_0/axi_clkgen_constr.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_hdmi_core_0/axi_hdmi_tx_constr.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_spdif_tx_core_0/axi_spdif_tx_constr.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_spdif_tx_dma_0/system_axi_spdif_tx_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_1/system_sys_mb_1.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_1/system_sys_mb_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_1/system_sys_mb_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_lmb_bram_0/system_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb1_axi_intc_0/system_sys_mb1_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb1_axi_intc_0/system_sys_mb1_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb1_axi_intc_0/system_sys_mb1_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_xbar_2/system_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_mailbox_0_0/system_mailbox_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_mailbox_0_0/system_mailbox_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_mutex_0_0/system_mutex_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_s05_data_fifo_0/system_s05_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_0/system_auto_us_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_1/system_auto_us_df_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_2/system_auto_us_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_2/system_auto_us_df_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_3/system_auto_us_df_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_3/system_auto_us_df_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_4/system_auto_us_df_4_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_4/system_auto_us_df_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_5/system_auto_us_df_5_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_5/system_auto_us_df_5_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_6/system_auto_us_df_6_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_6/system_auto_us_df_6_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_7/system_auto_us_df_7_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_7/system_auto_us_df_7_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_8/system_auto_us_df_8_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_auto_us_df_8/system_auto_us_df_8_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/system.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/imports/FPGA/Analog_HDL/hdl-hdl_2017_r1/projects/common/ac701/ac701_system_constr.xdc
set_property used_in_implementation false [get_files D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/imports/FPGA/Analog_HDL/hdl-hdl_2017_r1/projects/common/ac701/ac701_system_constr.xdc]

read_xdc D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/imports/FPGA/HDMI_AC701/ac701_project_dual/system_constr.xdc
set_property used_in_implementation false [get_files D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/imports/FPGA/HDMI_AC701/ac701_project_dual/system_constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_top -part xc7a200tfbg676-2 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


write_checkpoint -force -noxdef system_top.dcp

catch { report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb }
