set_property SRC_FILE_INFO {cfile:d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_0/system_sys_mb_0.xdc rfile:../../../Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_0/system_sys_mb_0.xdc id:1 order:EARLY scoped_inst:i_system_wrapper/system_i/mb0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xdc rfile:../../../Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_debug_0/system_sys_mb_debug_0.xdc id:2 order:EARLY scoped_inst:i_system_wrapper/system_i/sys_debug/U0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/constraints/system_axi_ddr_cntrl_0.xdc rfile:../../../Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0/user_design/constraints/system_axi_ddr_cntrl_0.xdc id:3 order:EARLY scoped_inst:i_system_wrapper/system_i/axi_ddr_cntrl} [current_design]
set_property SRC_FILE_INFO {cfile:d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_ethernet_clkgen_0/system_sys_ethernet_clkgen_0.xdc rfile:../../../Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_ethernet_clkgen_0/system_sys_ethernet_clkgen_0.xdc id:4 order:EARLY scoped_inst:i_system_wrapper/system_i/sys_ethernet_clkgen/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_eth_mac_0.xdc rfile:../../../Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_eth_mac_0.xdc id:5 order:EARLY scoped_inst:i_system_wrapper/system_i/axi_ethernet/inst/eth_mac/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_1/system_sys_mb_1.xdc rfile:../../../Final_Project_RTES.srcs/sources_1/bd/system/ip/system_sys_mb_1/system_sys_mb_1.xdc id:6 order:EARLY scoped_inst:i_system_wrapper/system_i/mb1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/imports/FPGA/Analog_HDL/hdl-hdl_2017_r1/projects/common/ac701/ac701_system_constr.xdc rfile:../../../Final_Project_RTES.srcs/sources_1/imports/FPGA/Analog_HDL/hdl-hdl_2017_r1/projects/common/ac701/ac701_system_constr.xdc id:7} [current_design]
set_property SRC_FILE_INFO {cfile:D:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/imports/FPGA/HDMI_AC701/ac701_project_dual/system_constr.xdc rfile:../../../Final_Project_RTES.srcs/sources_1/imports/FPGA/HDMI_AC701/ac701_project_dual/system_constr.xdc id:8} [current_design]
set_property SRC_FILE_INFO {cfile:d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/synth/bd_55cd_eth_buf_0.xdc rfile:../../../Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_0/synth/bd_55cd_eth_buf_0.xdc id:9 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ethernet/inst/eth_buf/U0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_eth_mac_0_clocks.xdc rfile:../../../Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_eth_mac_0_clocks.xdc id:10 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ethernet/inst/eth_mac/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/WORKSPACE/FPGA/Final_Project_RTES/Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0_clocks.xdc rfile:../../../Final_Project_RTES.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0_clocks.xdc id:11 order:LATE scoped_inst:i_system_wrapper/system_i/axi_spi/U0} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_ip_msg_config -idlist { DPOP-3 PDCN-1569 CDC-1 CDC-4 CDC-7 TIMING-9 TIMING-10 REQP-1839 }
set_property src_info {type:SCOPED_XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_ip_msg_config -idlist { CDC-1 CDCM-1 REQP-1851 TIMING-2 TIMING-4 TIMING-9 TIMING-10 TIMING-14 }
set_property src_info {type:SCOPED_XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6 [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB5 [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA5 [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y5 [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y6 [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y7 [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF4 [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF5 [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF3 [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:3 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE3 [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:3 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD3 [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC3 [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:3 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB4 [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:3 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA4 [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:3 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC2 [get_ports {ddr3_dq[16]}]
set_property src_info {type:SCOPED_XDC file:3 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB2 [get_ports {ddr3_dq[17]}]
set_property src_info {type:SCOPED_XDC file:3 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF2 [get_ports {ddr3_dq[18]}]
set_property src_info {type:SCOPED_XDC file:3 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE2 [get_ports {ddr3_dq[19]}]
set_property src_info {type:SCOPED_XDC file:3 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y1 [get_ports {ddr3_dq[20]}]
set_property src_info {type:SCOPED_XDC file:3 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y2 [get_ports {ddr3_dq[21]}]
set_property src_info {type:SCOPED_XDC file:3 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC1 [get_ports {ddr3_dq[22]}]
set_property src_info {type:SCOPED_XDC file:3 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB1 [get_ports {ddr3_dq[23]}]
set_property src_info {type:SCOPED_XDC file:3 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y3 [get_ports {ddr3_dq[24]}]
set_property src_info {type:SCOPED_XDC file:3 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W3 [get_ports {ddr3_dq[25]}]
set_property src_info {type:SCOPED_XDC file:3 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports {ddr3_dq[26]}]
set_property src_info {type:SCOPED_XDC file:3 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports {ddr3_dq[27]}]
set_property src_info {type:SCOPED_XDC file:3 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W4 [get_ports {ddr3_dq[28]}]
set_property src_info {type:SCOPED_XDC file:3 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports {ddr3_dq[29]}]
set_property src_info {type:SCOPED_XDC file:3 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W1 [get_ports {ddr3_dq[30]}]
set_property src_info {type:SCOPED_XDC file:3 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports {ddr3_dq[31]}]
set_property src_info {type:SCOPED_XDC file:3 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G2 [get_ports {ddr3_dq[32]}]
set_property src_info {type:SCOPED_XDC file:3 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D1 [get_ports {ddr3_dq[33]}]
set_property src_info {type:SCOPED_XDC file:3 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E1 [get_ports {ddr3_dq[34]}]
set_property src_info {type:SCOPED_XDC file:3 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E2 [get_ports {ddr3_dq[35]}]
set_property src_info {type:SCOPED_XDC file:3 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F2 [get_ports {ddr3_dq[36]}]
set_property src_info {type:SCOPED_XDC file:3 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A2 [get_ports {ddr3_dq[37]}]
set_property src_info {type:SCOPED_XDC file:3 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3 [get_ports {ddr3_dq[38]}]
set_property src_info {type:SCOPED_XDC file:3 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2 [get_ports {ddr3_dq[39]}]
set_property src_info {type:SCOPED_XDC file:3 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports {ddr3_dq[40]}]
set_property src_info {type:SCOPED_XDC file:3 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D3 [get_ports {ddr3_dq[41]}]
set_property src_info {type:SCOPED_XDC file:3 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports {ddr3_dq[42]}]
set_property src_info {type:SCOPED_XDC file:3 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B4 [get_ports {ddr3_dq[43]}]
set_property src_info {type:SCOPED_XDC file:3 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports {ddr3_dq[44]}]
set_property src_info {type:SCOPED_XDC file:3 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports {ddr3_dq[45]}]
set_property src_info {type:SCOPED_XDC file:3 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D5 [get_ports {ddr3_dq[46]}]
set_property src_info {type:SCOPED_XDC file:3 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E5 [get_ports {ddr3_dq[47]}]
set_property src_info {type:SCOPED_XDC file:3 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F4 [get_ports {ddr3_dq[48]}]
set_property src_info {type:SCOPED_XDC file:3 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G4 [get_ports {ddr3_dq[49]}]
set_property src_info {type:SCOPED_XDC file:3 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K6 [get_ports {ddr3_dq[50]}]
set_property src_info {type:SCOPED_XDC file:3 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K7 [get_ports {ddr3_dq[51]}]
set_property src_info {type:SCOPED_XDC file:3 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K8 [get_ports {ddr3_dq[52]}]
set_property src_info {type:SCOPED_XDC file:3 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L8 [get_ports {ddr3_dq[53]}]
set_property src_info {type:SCOPED_XDC file:3 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J5 [get_ports {ddr3_dq[54]}]
set_property src_info {type:SCOPED_XDC file:3 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J6 [get_ports {ddr3_dq[55]}]
set_property src_info {type:SCOPED_XDC file:3 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G6 [get_ports {ddr3_dq[56]}]
set_property src_info {type:SCOPED_XDC file:3 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H6 [get_ports {ddr3_dq[57]}]
set_property src_info {type:SCOPED_XDC file:3 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F7 [get_ports {ddr3_dq[58]}]
set_property src_info {type:SCOPED_XDC file:3 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F8 [get_ports {ddr3_dq[59]}]
set_property src_info {type:SCOPED_XDC file:3 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports {ddr3_dq[60]}]
set_property src_info {type:SCOPED_XDC file:3 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H8 [get_ports {ddr3_dq[61]}]
set_property src_info {type:SCOPED_XDC file:3 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D6 [get_ports {ddr3_dq[62]}]
set_property src_info {type:SCOPED_XDC file:3 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E6 [get_ports {ddr3_dq[63]}]
set_property src_info {type:SCOPED_XDC file:3 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N6 [get_ports {ddr3_addr[13]}]
set_property src_info {type:SCOPED_XDC file:3 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L7 [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:3 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L5 [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:3 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N7 [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:3 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K3 [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:3 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H1 [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:3 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K1 [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M7 [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H2 [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P1 [get_ports {ddr3_ras_n}]
set_property src_info {type:SCOPED_XDC file:3 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports {ddr3_cas_n}]
set_property src_info {type:SCOPED_XDC file:3 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {ddr3_we_n}]
set_property src_info {type:SCOPED_XDC file:3 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N8 [get_ports {ddr3_reset_n}]
set_property src_info {type:SCOPED_XDC file:3 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {ddr3_cke[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {ddr3_odt[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC6 [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC4 [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA3 [get_ports {ddr3_dm[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {ddr3_dm[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:558 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G1 [get_ports {ddr3_dm[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F3 [get_ports {ddr3_dm[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G5 [get_ports {ddr3_dm[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H9 [get_ports {ddr3_dm[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports {sys_clk_p}]
set_property src_info {type:SCOPED_XDC file:3 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {sys_clk_n}]
set_property src_info {type:SCOPED_XDC file:3 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD5 [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE5 [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:611 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD1 [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE1 [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V3 [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:629 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C1 [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B1 [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B5 [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A5 [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J4 [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:665 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H4 [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H7 [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:677 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:682 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:687 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:691 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:3 line:692 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:3 line:693 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:3 line:694 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:3 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:3 line:696 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:3 line:697 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:3 line:698 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y15 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:3 line:699 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y14 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:3 line:700 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y13 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:3 line:701 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y12 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:3 line:703 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:3 line:704 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:3 line:705 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:3 line:706 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:3 line:710 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y15 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:3 line:711 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y14 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:3 line:712 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y13 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:3 line:713 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y12 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:3 line:717 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:718 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:719 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:720 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:721 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:722 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:723 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:724 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y15 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:725 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y14 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:726 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y13 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:727 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y12 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:729 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:730 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:731 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:732 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:733 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y15 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:734 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y14 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:735 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y13 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:736 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y12 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:3 line:738 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:3 line:739 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:3 line:740 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:3 line:742 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:3 line:743 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:3 line:744 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:3 line:746 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y93 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:3 line:747 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y81 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:3 line:748 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y69 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:3 line:749 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y57 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:3 line:750 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y193 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:3 line:751 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y181 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:3 line:752 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y169 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:3 line:753 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y157 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:3 line:755 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:SCOPED_XDC file:3 line:756 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/gen_ui_extra_clocks.mmcm_i}]
set_property src_info {type:SCOPED_XDC file:3 line:765 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_property src_info {type:SCOPED_XDC file:3 line:766 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:SCOPED_XDC file:4 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.05
set_property src_info {type:SCOPED_XDC file:5 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/flow/rx_pause/pause*to_tx_reg[*]}] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/flow/tx_pause/count_set*reg}] 32 -datapath_only
set_property src_info {type:SCOPED_XDC file:5 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/flow/rx_pause/pause*to_tx_reg[*]}] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/flow/tx_pause/pause_count*reg[*]}] 32 -datapath_only
set_property src_info {type:SCOPED_XDC file:5 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/flow/rx_pause/pause_req_to_tx_int_reg}] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/flow/tx_pause/sync_good_rx/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:5 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/*statistics_counters/rd_data_ref_reg[*]}] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/*statistics_counters/ip2bus_data_reg[*]}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:5 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/*statistics_counters/response_toggle_reg}] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/*statistics_counters/sync_response/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:5 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/*statistics_counters/request_toggle_reg}] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/*statistics_counters/sync_request/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:5 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/addr_filter_top/addr_regs.promiscuous_mode_reg_reg}] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/addr_filter_top/address_filter_inst/resync_promiscuous_mode/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:5 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/addr_filter_top/addr_regs.filter_enable_reg_reg[*]}] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/addr_filter_top/address_filter_inst/address_filters[*].sync_enable/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:5 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/*managen/conf/update_pause_ad_int_reg}] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/addr_filter_top/address_filter_inst/sync_update/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:5 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/sync_int_tx_rst_mgmt_tx_clk/sync_rst1_reg}] -to [get_cells {tri_mode_ethernet_mac_i/enable_gen/reset90gen/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_ip_msg_config -idlist { DPOP-3 PDCN-1569 CDC-1 CDC-4 CDC-7 TIMING-9 TIMING-10 REQP-1839 DPIP-2 DPOP-4 }
set_property src_info {type:XDC file:7 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  U4    IOSTANDARD  LVCMOS15} [get_ports sys_rst]
set_property src_info {type:XDC file:7 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  R3    IOSTANDARD  DIFF_SSTL15 DIFF_TERM TRUE} [get_ports sys_clk_p]
set_property src_info {type:XDC file:7 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  P3    IOSTANDARD  DIFF_SSTL15 DIFF_TERM TRUE} [get_ports sys_clk_n]
set_property src_info {type:XDC file:7 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN V18    IOSTANDARD  LVCMOS18} [get_ports phy_reset_n]
set_property src_info {type:XDC file:7 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN W18    IOSTANDARD  LVCMOS18} [get_ports phy_mdc]
set_property src_info {type:XDC file:7 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN T14    IOSTANDARD  LVCMOS18} [get_ports phy_mdio]
set_property src_info {type:XDC file:7 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN U22    IOSTANDARD  LVCMOS18} [get_ports phy_tx_clk]
set_property src_info {type:XDC file:7 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN T15    IOSTANDARD  LVCMOS18} [get_ports phy_tx_ctrl]
set_property src_info {type:XDC file:7 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN T17    IOSTANDARD  LVCMOS18} [get_ports phy_tx_data[3]]
set_property src_info {type:XDC file:7 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN T18    IOSTANDARD  LVCMOS18} [get_ports phy_tx_data[2]]
set_property src_info {type:XDC file:7 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN U15    IOSTANDARD  LVCMOS18} [get_ports phy_tx_data[1]]
set_property src_info {type:XDC file:7 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN U16    IOSTANDARD  LVCMOS18} [get_ports phy_tx_data[0]]
set_property src_info {type:XDC file:7 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN U21    IOSTANDARD  LVCMOS18} [get_ports phy_rx_clk]
set_property src_info {type:XDC file:7 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN U14    IOSTANDARD  LVCMOS18} [get_ports phy_rx_ctrl]
set_property src_info {type:XDC file:7 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN V14    IOSTANDARD  LVCMOS18} [get_ports phy_rx_data[3]]
set_property src_info {type:XDC file:7 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN V16    IOSTANDARD  LVCMOS18} [get_ports phy_rx_data[2]]
set_property src_info {type:XDC file:7 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN V17    IOSTANDARD  LVCMOS18} [get_ports phy_rx_data[1]]
set_property src_info {type:XDC file:7 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN U17    IOSTANDARD  LVCMOS18} [get_ports phy_rx_data[0]]
set_property src_info {type:XDC file:7 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  T19   IOSTANDARD  LVCMOS18} [get_ports uart_sin]
set_property src_info {type:XDC file:7 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  U19   IOSTANDARD  LVCMOS18} [get_ports uart_sout]
set_property src_info {type:XDC file:7 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  J26   IOSTANDARD  LVCMOS25} [get_ports fan_pwm]
set_property src_info {type:XDC file:7 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  L20   IOSTANDARD  LVCMOS33} [get_ports gpio_lcd[6]]   ; ## lcd_e
set_property src_info {type:XDC file:7 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  L23   IOSTANDARD  LVCMOS33} [get_ports gpio_lcd[5]]   ; ## lcd_rs
set_property src_info {type:XDC file:7 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  L24   IOSTANDARD  LVCMOS33} [get_ports gpio_lcd[4]]   ; ## lcd_rw
set_property src_info {type:XDC file:7 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  L22   IOSTANDARD  LVCMOS33} [get_ports gpio_lcd[3]]   ; ## lcd_db[7]
set_property src_info {type:XDC file:7 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  M25   IOSTANDARD  LVCMOS33} [get_ports gpio_lcd[2]]   ; ## lcd_db[6]
set_property src_info {type:XDC file:7 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  M24   IOSTANDARD  LVCMOS33} [get_ports gpio_lcd[1]]   ; ## lcd_db[5]
set_property src_info {type:XDC file:7 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  L25   IOSTANDARD  LVCMOS33} [get_ports gpio_lcd[0]]   ; ## lcd_db[4]
set_property src_info {type:XDC file:7 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  R8    IOSTANDARD  SSTL15}   [get_ports gpio_bd[0]]    ; ## GPIO_DIP_SW0
set_property src_info {type:XDC file:7 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  P8    IOSTANDARD  SSTL15}   [get_ports gpio_bd[1]]    ; ## GPIO_DIP_SW1
set_property src_info {type:XDC file:7 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  R7    IOSTANDARD  SSTL15}   [get_ports gpio_bd[2]]    ; ## GPIO_DIP_SW2
set_property src_info {type:XDC file:7 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  R6    IOSTANDARD  SSTL15}   [get_ports gpio_bd[3]]    ; ## GPIO_DIP_SW3
set_property src_info {type:XDC file:7 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  P6    IOSTANDARD  LVCMOS15} [get_ports gpio_bd[4]]    ; ## GPIO_SW_N
set_property src_info {type:XDC file:7 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  U5    IOSTANDARD  SSTL15}   [get_ports gpio_bd[5]]    ; ## GPIO_SW_E
set_property src_info {type:XDC file:7 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  T5    IOSTANDARD  SSTL15}   [get_ports gpio_bd[6]]    ; ## GPIO_SW_S
set_property src_info {type:XDC file:7 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  R5    IOSTANDARD  SSTL15}   [get_ports gpio_bd[7]]    ; ## GPIO_SW_W
set_property src_info {type:XDC file:7 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  U6    IOSTANDARD  SSTL15}   [get_ports gpio_bd[8]]    ; ## GPIO_SW_C
set_property src_info {type:XDC file:7 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  M26   IOSTANDARD  LVCMOS33} [get_ports gpio_bd[9]]    ; ## GPIO_LED_0_LS
set_property src_info {type:XDC file:7 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  T24   IOSTANDARD  LVCMOS33} [get_ports gpio_bd[10]]   ; ## GPIO_LED_1_LS
set_property src_info {type:XDC file:7 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  T25   IOSTANDARD  LVCMOS33} [get_ports gpio_bd[11]]   ; ## GPIO_LED_2_LS
set_property src_info {type:XDC file:7 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  R26   IOSTANDARD  LVCMOS33} [get_ports gpio_bd[12]]   ; ## GPIO_LED_3_LS
set_property src_info {type:XDC file:7 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  R17   IOSTANDARD  LVCMOS33} [get_ports iic_rstn]
set_property src_info {type:XDC file:7 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  N18   IOSTANDARD  LVCMOS33  DRIVE 8 SLEW SLOW} [get_ports iic_scl]
set_property src_info {type:XDC file:7 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  K25   IOSTANDARD  LVCMOS33  DRIVE 8 SLEW SLOW} [get_ports iic_sda]
set_property src_info {type:XDC file:8 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  V21   IOSTANDARD  LVCMOS18} [get_ports hdmi_out_clk]
set_property src_info {type:XDC file:8 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  AA22  IOSTANDARD  LVCMOS18} [get_ports hdmi_hsync]
set_property src_info {type:XDC file:8 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  AC26  IOSTANDARD  LVCMOS18} [get_ports hdmi_vsync]
set_property src_info {type:XDC file:8 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  AB26  IOSTANDARD  LVCMOS18} [get_ports hdmi_data_e]
set_property src_info {type:XDC file:8 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  AA24  IOSTANDARD  LVCMOS18} [get_ports hdmi_data[0]]
set_property src_info {type:XDC file:8 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  Y25   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[1]]
set_property src_info {type:XDC file:8 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  Y26   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[2]]
set_property src_info {type:XDC file:8 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  V26   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[3]]
set_property src_info {type:XDC file:8 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  W26   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[4]]
set_property src_info {type:XDC file:8 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  W25   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[5]]
set_property src_info {type:XDC file:8 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  W24   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[6]]
set_property src_info {type:XDC file:8 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  U26   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[7]]
set_property src_info {type:XDC file:8 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  U25   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[8]]
set_property src_info {type:XDC file:8 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  V24   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[9]]
set_property src_info {type:XDC file:8 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  U20   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[10]]
set_property src_info {type:XDC file:8 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  W23   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[11]]
set_property src_info {type:XDC file:8 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  W20   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[12]]
set_property src_info {type:XDC file:8 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  U24   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[13]]
set_property src_info {type:XDC file:8 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  Y20   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[14]]
set_property src_info {type:XDC file:8 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  V23   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[15]]
set_property src_info {type:XDC file:8 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  AA23  IOSTANDARD  LVCMOS18} [get_ports hdmi_data[16]]
set_property src_info {type:XDC file:8 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  AA25  IOSTANDARD  LVCMOS18} [get_ports hdmi_data[17]]
set_property src_info {type:XDC file:8 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  AB25  IOSTANDARD  LVCMOS18} [get_ports hdmi_data[18]]
set_property src_info {type:XDC file:8 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  AC24  IOSTANDARD  LVCMOS18} [get_ports hdmi_data[19]]
set_property src_info {type:XDC file:8 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  AB24  IOSTANDARD  LVCMOS18} [get_ports hdmi_data[20]]
set_property src_info {type:XDC file:8 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  Y22   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[21]]
set_property src_info {type:XDC file:8 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  Y23   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[22]]
set_property src_info {type:XDC file:8 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  V22   IOSTANDARD  LVCMOS18} [get_ports hdmi_data[23]]
set_property src_info {type:XDC file:8 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict  {PACKAGE_PIN  Y21   IOSTANDARD  LVCMOS18} [get_ports spdif]
set_property src_info {type:SCOPED_XDC file:9 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay  -from [get_cells {*TX_PAUSE_FRAME_CROSS_I/clk_a2b_bus_reg[*]}]   -to [get_cells  -hier -regexp {.*TX_PAUSE_FRAME_CROSS_I.*ClkBAxiEthBaEClkCrsBusOut_reg.*} -filter {IS_SEQUENTIAL=="1"}] 8 -datapath_only
set_property src_info {type:SCOPED_XDC file:9 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -of [all_fanin -flat [get_pins -hier -regexp {.*/ClkBAxiEthBClkCrsBusOut_reg.*D}]] -filter {IS_SEQUENTIAL=="1" && NAME !~ "*ClkBAxiEthBClkCrsBusOut*"}] -to [get_pins -hier -regexp {.*/ClkBAxiEthBClkCrsBusOut_reg.*D}] 8 -datapath_only
set_property src_info {type:SCOPED_XDC file:9 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {*RCV_INTFCE_I/RX_AXISTREAM_IF_I/rxs_mem_last_read_out_ptr_gray_d1_reg[*]}] -to [get_cells {*RCV_INTFCE_I/NO_INCLUDE_RX_VLAN.RX_EMAC_IF_I/SYNC_RXS_LAST_READ_GRAY_PROCESS[*].SYNC_RXS_LAST_READ_GRAY/data_sync0_i}]  8 -datapath_only
set_property src_info {type:SCOPED_XDC file:9 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {*RCV_INTFCE_I/RX_AXISTREAM_IF_I/rxd_mem_last_read_out_ptr_gray_d1_reg[*]}] -to [get_cells {*RCV_INTFCE_I/NO_INCLUDE_RX_VLAN.RX_EMAC_IF_I/SYNC_RXD_LAST_READ_GRAY_PROCESS[*].SYNC_RXD_LAST_READ_GRAY/data_sync0_i}]  8 -datapath_only
set_property src_info {type:SCOPED_XDC file:10 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -rise_from [get_clocks i_system_wrapper/system_i/axi_ethernet/inst/eth_mac/inst_rgmii_rx_clk] -rise_to [get_clocks -of_objects [get_ports phy_rx_clk]] -hold
set_property src_info {type:SCOPED_XDC file:10 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -fall_from [get_clocks i_system_wrapper/system_i/axi_ethernet/inst/eth_mac/inst_rgmii_rx_clk] -fall_to [get_clocks -of_objects [get_ports phy_rx_clk]] -hold
set_property src_info {type:SCOPED_XDC file:10 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -rise_from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ethernet/inst/eth_mac/inst/tri_mode_ethernet_mac_support_clocking_i/mmcm_adv_inst/CLKOUT0]] -rise_to [get_clocks i_system_wrapper/system_i/axi_ethernet/inst/eth_mac/inst_rgmii_tx_clk] -hold
set_property src_info {type:SCOPED_XDC file:10 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -fall_from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ethernet/inst/eth_mac/inst/tri_mode_ethernet_mac_support_clocking_i/mmcm_adv_inst/CLKOUT0]] -fall_to [get_clocks i_system_wrapper/system_i/axi_ethernet/inst/eth_mac/inst_rgmii_tx_clk] -hold
set_property src_info {type:SCOPED_XDC file:10 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_ports phy_rx_clk]] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/*statistics_counters/general_statisic_control[*].general_statisics/sync_inc_vector/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:10 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_ports phy_rx_clk]] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/*statistics_counters/frame_size_bin_control1[*].frame_size_stats1/sync_inc_vector/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:10 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_ports phy_rx_clk]] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/*statistics_counters/frame_size_bin_control2[*].frame_size_stats2/sync_inc_vector/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:10 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_ports phy_rx_clk]] -to [get_cells {tri_mode_ethernet_mac_i/bd_55cd_eth_mac_0_core/*statistics_counters/*/accum_gray_resync[*].sync_accum_gray_i/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:10 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_i/axi4_lite_ipif/axi4_lite_ipif_top_wrapper/axi_lite_top/*/bus2ip_addr_i_reg[*]}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ethernet/inst/eth_mac/inst/tri_mode_ethernet_mac_support_clocking_i/mmcm_adv_inst/CLKOUT0]] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:11 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~*RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/*rd_pntr_gc_reg[*]}] -to [get_cells -hierarchical -filter {NAME =~*RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/*gsync_stage[1].wr_stg_inst/Q_reg_reg[*]}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_spi/U0/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:11 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~*RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/*wr_pntr_gc_reg[*]}] -to [get_cells -hierarchical -filter {NAME =~*RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/*gsync_stage[1].rd_stg_inst/Q_reg_reg[*]}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_spi/U0/ext_spi_clk]]]
set_property src_info {type:SCOPED_XDC file:11 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~*TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/*rd_pntr_gc_reg[*]}] -to [get_cells -hierarchical -filter {NAME =~*TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/*gsync_stage[1].wr_stg_inst/Q_reg_reg[*]}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_spi/U0/ext_spi_clk]]]
set_property src_info {type:SCOPED_XDC file:11 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~*TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/*wr_pntr_gc_reg[*]}] -to [get_cells -hierarchical -filter {NAME =~*TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/*gsync_stage[1].rd_stg_inst/Q_reg_reg[*]}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_spi/U0/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:11 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_bus_skew -from [get_cells [list {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[0]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[1]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[2]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[3]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[0]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[1]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[2]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[3]}]] -to [get_cells [list {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[0]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[1]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[2]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[3]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[0]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[1]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[2]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[3]}]] 10.000
set_property src_info {type:SCOPED_XDC file:11 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_bus_skew -from [get_cells [list {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[0]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[1]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[2]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[3]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[0]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[1]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[2]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.rd_pntr_gc_reg[3]}]] -to [get_cells [list {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[0]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[1]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[2]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[3]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[0]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[1]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[2]} {i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/USE_2N_DEPTH.V6_S6_AND_LATER.I_ASYNC_FIFO_BRAM/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gnxpm_cdc.gsync_stage[1].wr_stg_inst/Q_reg_reg[3]}]] 10.000
